[django.db.backends]: (0.000) SELECT `rapidsms_backend`.`name` FROM `rapidsms_backend`; args=()
[django.db.backends]: (0.000) SELECT `rapidsms_app`.`module` FROM `rapidsms_app`; args=()
[router]: Starting RapidSMS...
[router]: starting backend
[router]: starting backend
[backend/att]: Connecting and booting via pyGSM...
[backend/att]: debug: Booting
[backend/att]: debug: Connecting
[app/handlers]: Registered: EchoHandler, PingHandler
[router]: caught exception in backend pyGSM: could not open port /dev/ttyUSB2: [Errno 2] No such file or directory: '/dev/ttyUSB2'
[backend/att]: An exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/RapidSMS-0.9.6a-py2.7.egg/rapidsms/router.py", line 127, in _start_backend
    started = backend.start()
  File "/usr/local/lib/python2.7/dist-packages/RapidSMS-0.9.6a-py2.7.egg/rapidsms/backends/gsm.py", line 159, in start
    self.modem = pygsm.GsmModem(logger=self.gsm_log, **self.modem_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygsm/gsmmodem.py", line 126, in __init__
    self.boot()
  File "/usr/local/lib/python2.7/dist-packages/pygsm/gsmmodem.py", line 240, in boot
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/pygsm/gsmmodem.py", line 176, in connect
    **self.device_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pygsm/devicewrapper.py", line 33, in __init__
    self.device = serial.Serial(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/serial/serialutil.py", line 260, in __init__
    self.open()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 276, in open
    raise SerialException("could not open port %s: %s" % (self._port, msg))
SerialException: could not open port /dev/ttyUSB2: [Errno 2] No such file or directory: '/dev/ttyUSB2'
[router]: waiting 15 seconds before retrying
[router]: Started
[router]: Caught KeyboardInterrupt
[router]: Stopping...
[router]: returning from _start_backend
[router]: backend <backend: message_tester> terminated normally
[router]: Stopped
[django.db.backends]: (0.000) SELECT `rapidsms_backend`.`name` FROM `rapidsms_backend`; args=()
[django.db.backends]: (0.000) SELECT `rapidsms_app`.`module` FROM `rapidsms_app`; args=()
[router]: Starting RapidSMS...
[router]: starting backend
[backend/att]: Connecting and booting via pyGSM...
[backend/att]: debug: Booting
[backend/att]: debug: Connecting
[router]: starting backend
[app/handlers]: Registered: EchoHandler, PingHandler
[backend/att]: write: 'ATE0\r'
[router]: Started
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMEE=1\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+WIND=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'COMMAND NOT SUPPORT\r\n'
[backend/att]: write: 'AT+CSMS=1\r'
[backend/att]: read: '\r\n'
[backend/att]: read: '+CSMS: 1,1,1\r\n'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMGF=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CNMI=2,2,0,0,0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: '+CMS ERROR: 303\r\n'
[backend/att]: write: 'AT+CMGL=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: debug: Booting
[backend/att]: debug: Connecting
[backend/att]: write: 'ATE0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMEE=1\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+WIND=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'COMMAND NOT SUPPORT\r\n'
[backend/att]: write: 'AT+CSMS=1\r'
[backend/att]: read: '\r\n'
[backend/att]: read: '+CSMS: 1,1,1\r\n'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMGF=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CNMI=2,2,0,0,0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: '+CMS ERROR: 303\r\n'
[backend/att]: write: 'AT+CMGL=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: Polling modem for messages
[backend/att]: write: 'AT\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMGL=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: Polling modem for messages
[backend/att]: write: 'AT\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMGL=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: Polling modem for messages
[backend/att]: write: 'AT\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMGL=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: Polling modem for messages
[backend/att]: write: 'AT\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMGL=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: Polling modem for messages
[backend/att]: write: 'AT\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: write: 'AT+CMGL=0\r'
[backend/att]: read: '\r\n'
[backend/att]: read: 'OK\r\n'
[backend/att]: Polling modem for messages
[backend/att]: write: 'AT\r'
[backend/att]: debug: Disconnecting
[router]: caught exception in backend pyGSM: write failed: [Errno 5] Input/output error
[backend/att]: An exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/RapidSMS-0.9.6a-py2.7.egg/rapidsms/router.py", line 127, in _start_backend
    started = backend.start()
  File "/usr/local/lib/python2.7/dist-packages/RapidSMS-0.9.6a-py2.7.egg/rapidsms/backends/gsm.py", line 167, in start
    BackendBase.start(self)
  File "/usr/local/lib/python2.7/dist-packages/RapidSMS-0.9.6a-py2.7.egg/rapidsms/backends/base.py", line 51, in start
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/RapidSMS-0.9.6a-py2.7.egg/rapidsms/backends/gsm.py", line 132, in run
    msg = self.modem.next_message()
  File "/usr/local/lib/python2.7/dist-packages/pygsm/gsmmodem.py", line 562, in next_message
    self.ping()
  File "/usr/local/lib/python2.7/dist-packages/pygsm/gsmmodem.py", line 524, in ping
    self.command("AT")
  File "/usr/local/lib/python2.7/dist-packages/pygsm/gsmmodem.py", line 346, in command
    self._write(cmd + write_term)
  File "/usr/local/lib/python2.7/dist-packages/pygsm/gsmmodem.py", line 267, in _write
    self.device.write(str)
  File "/usr/local/lib/python2.7/dist-packages/pygsm/devicewrapper.py", line 43, in write
    self.device.write(str)
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 485, in write
    raise SerialException('write failed: %s' % (v,))
SerialException: write failed: [Errno 5] Input/output error
[router]: waiting 15 seconds before retrying
[router]: starting backend
[backend/att]: Connecting and booting via pyGSM...
[backend/att]: debug: Booting
[backend/att]: debug: Connecting
[backend/att]: debug: Disconnecting
[router]: caught exception in backend pyGSM: could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
